# -*- coding: utf-8 -*-
"""Evaluacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6tap-SVmHo2a7keamqg7M0nZEiypsQT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el archivo CSV
df = pd.read_csv('listings.csv')
df

df.info()

# (a) Seleccionar registros de 5 "host name" diferentes
anfitriones_unicos = df['host_name'].dropna().unique()[:5]
df_a = df[df['host_name'].isin(anfitriones_unicos)]
df_a.to_csv("filtro_a_nombre_anfitrion.csv")
print(df_a.head())

# (b) Filtrar los hosts que se unieron antes del 2019
df_b = df_a[pd.to_datetime(df_a['host_since']) < '2019-01-01']
df_b.to_csv("filtro_b_fecha_anfitrion.csv")
print(df_b.head())

# (c) Filtrar los hosts que responden "a más tardar en 1 día"
valores_validos_respuesta = ["within an hour", "within a few hours"]
df_c = df_b[df_b['host_response_time'].isin(valores_validos_respuesta)]
df_c.to_csv("filtro_c_tiempo_respuesta.csv")
print("Registros después del filtro (c):", len(df_c))
print(df_c.head())

# (d) Ver los valores únicos en la columna accommodates antes de filtrar
print("Valores únicos en accommodates:", df_c['accommodates'].dropna().unique())

# (d) Filtrar los registros que tengan al menos 5 accommodates
df_d = df_c[pd.to_numeric(df_c['accommodates'], errors='coerce') >= 5]
df_d.to_csv("filtro_d_acomoda.csv")
print("Registros después del filtro (d):", len(df_d))
print(df_d.head())

# (e) Filtrar los registros de tipo de cuarto "Entire home" y "Private room"
df_e = df_d[df_d['room_type'].isin(["Entire home/apt", "Private room"])]
df_e.to_csv("filtro_e_tipo_cuarto.csv")
print(df_e.head())

# (f) Filtrar registros que a lo mucho cuenten con 4 camas
df_f = df_e[pd.to_numeric(df_e['beds'], errors='coerce') <= 4]
df_f.to_csv("filtro_f_camas.csv", index=False)
print(df_f.head())

# (g) Filtrar registros que tengan 1 baño o sean superhost y todos sean instant_bookable
df_g = df_f[(pd.to_numeric(df_f['bathrooms']) == 1) | (df_f['host_is_superhost'] == 't')]
df_g = df_g[df_g['instant_bookable'] == 't']
df_g.to_csv("filtro_g_baño_superhost.csv")
print(df_g.head())

# (h) Filtrar los registros donde review_scores_cleanliness < 3 y review_scores_rating > 3
df_h = df_g[(pd.to_numeric(df_g['review_scores_cleanliness'], ) < 3) &
            (pd.to_numeric(df_g['review_scores_rating']) > 3)]
df_h.to_csv("filtro_h_puntajes_resenas.csv", index=False)
print(df_h.head())